global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'custom-exporter'
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['incidentio-exporter:9193']
