{
 "title": "Overview",
 "description": "High level overview of all incidents created in https://incident.io",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Incidents Total",
   "type": "timeseries",
   "description": "Shows the count of all incidents created on Incident.io.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "incidentio_exporter_total_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incidents by status",
   "type": "bargauge",
   "description": "Shows the count of all incidents with their status created on Incident.io.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "incidentio_exporter_status_count{}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Incidents by severity",
   "type": "bargauge",
   "description": "Shows the count of all incidents with their severity type created on Incident.io",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "incidentio_exporter_severity_count",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Incidents by environment",
   "type": "bargauge",
   "description": "Shows the count of all incidents with their environment type created on Incident.io",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "incidentio_exporter_environment_count",
     "legendFormat": "{{environment}}"
    }
   ]
  }
 ]
}